### ISSUE TITLE
Files Script Output

### ISSUE THREAD

**Issue by hubdows** [f5devcentral/f5-ihealth-api-examples#1]
Hi, looking for a little clarification about the files script. When I run it the only output I see is:

  Retrieving files for 119xxxxxx 
  Authenticating
  {"expires": 1565201xxx}Authentication successful 
  platform=C109
  family=0xF2000000
  host=C109
  systype=0x8a

Shouldn't there be a file list?  Using debug I can see the file information in the XML, but the listing is not displayed, and no files are downloaded. What am I missing?

**Comment by jon-gross-f5** [comment]
Hey @hubdows.

No, the script is actually just an example.  It does pull a file list, and picks one of the files ("/PLATFORM") and displays the contents of that single file.

The script should be adapted to suite your needs - you could change it to print the file list if you like.

**Comment by hubdows** [comment]
Thanks, I realized that a few minutes after posting. Thanks @jon-gross-f5, great job on these scripts!
